In [1]:
import pandas as pd

In [20]:
df1 = pd.read_csv('data/salad_yolo_lm_and_z.csv')
df2 = pd.read_csv('data/simu_yolo_lm_and_z.csv')
df_d = pd.read_csv('data/depths_added.csv')

In [36]:
df = pd.concat([df1, df2],ignore_index=True)

In [37]:
depth = df_d.iloc[:,-4:-2]
depth

      lh_depth_dist  rh_depth_dist
0       -128.411926   -2014.397278
1     -10972.939575   -6049.359009
2      -3838.286377  -18578.716064
3       -814.518860    -905.653381
4      -1761.761719   -1246.901855
...             ...            ...
4753     877.946289    6519.351683
4754   -2146.814453    -174.041504
4755   -1189.540039    4339.987671
4756     901.244385    6482.765343
4757    1120.292725    4676.091797

[4758 rows x 2 columns]

In [38]:
df.iloc[:, :-2]

,l_hand_min_x,l_hand_min_y,l_hand_width,l_hand_height,r_hand_min_x,r_hand_min_y,r_hand_width,r_hand_height,object_min_x,object_min_y,...,r18z,r19x,r19y,r19z,r20x,r20y,r20z,r21x,r21y,r21z
0,1920,0,0,0,1001,682,142,64,869,576,...,0.026158,100,-3,0.028874,86,-14,0.027805,78,-27,0.027370
1,1920,1080,0,0,1539,608,209,259,667,243,...,-0.018813,504,-358,-0.025364,479,-333,-0.030282,451,-321,-0.033694
2,1171,587,118,168,1920,1080,0,0,712,351,...,0.000000,-334,422,0.000000,-334,422,0.000000,-334,422,0.000000
3,1326,521,101,62,0,1080,0,0,1046,267,...,0.000000,35,403,0.000000,35,403,0.000000,35,403,0.000000
4,1118,351,182,198,1366,647,105,195,564,484,...,0.028569,296,-71,0.025162,273,-59,0.019886,251,-55,0.016823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753,972,270,148,176,0,0,0,0,920,926,...,0.000000,1023,985,0.000000,1023,985,0.000000,1023,985,0.000000
4754,877,749,188,121,1003,521,135,97,981,603,...,0.013393,169,116,0.012401,166,104,0.011373,166,94,0.011249
4755,866,400,172,127,0,0,0,0,943,664,...,0.000000,1004,727,0.000000,1004,727,0.000000,1004,727,0.000000
4756,1174,875,123,53,0,0,0,0,1097,964,...,0.000000,1222,1022,0.000000,1222,1022,0.000000,1222,1022,0.000000
4757,687,236,153,113,0,0,0,0,968,877,...,0.000000,988,974,0.000000,988,974,0.000000,988,974,0.000000

In [42]:
df_f = pd.concat([df.iloc[:, :-2], depth, df.iloc[:,-2:]], axis=1)

In [43]:
df_f

,l_hand_min_x,l_hand_min_y,l_hand_width,l_hand_height,r_hand_min_x,r_hand_min_y,r_hand_width,r_hand_height,object_min_x,object_min_y,...,r20x,r20y,r20z,r21x,r21y,r21z,lh_depth_dist,rh_depth_dist,picture_name,grasp
0,1920,0,0,0,1001,682,142,64,869,576,...,86,-14,0.027805,78,-27,0.027370,-128.411926,-2014.397278,salad16085.png,none
1,1920,1080,0,0,1539,608,209,259,667,243,...,479,-333,-0.030282,451,-321,-0.033694,-10972.939575,-6049.359009,salad09942.png,none
2,1171,587,118,168,1920,1080,0,0,712,351,...,-334,422,0.000000,-334,422,0.000000,-3838.286377,-18578.716064,salad11706.png,none
3,1326,521,101,62,0,1080,0,0,1046,267,...,35,403,0.000000,35,403,0.000000,-814.518860,-905.653381,salad04018.png,none
4,1118,351,182,198,1366,647,105,195,564,484,...,273,-59,0.019886,251,-55,0.016823,-1761.761719,-1246.901855,salad16039.png,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753,972,270,148,176,0,0,0,0,920,926,...,1023,985,0.000000,1023,985,0.000000,877.946289,6519.351683,simulation02823.png,precision
4754,877,749,188,121,1003,521,135,97,981,603,...,166,104,0.011373,166,94,0.011249,-2146.814453,-174.041504,simulation00768.png,precision
4755,866,400,172,127,0,0,0,0,943,664,...,1004,727,0.000000,1004,727,0.000000,-1189.540039,4339.987671,simulation02895.png,precision
4756,1174,875,123,53,0,0,0,0,1097,964,...,1222,1022,0.000000,1222,1022,0.000000,901.244385,6482.765343,simulation00537.png,precision
4757,687,236,153,113,0,0,0,0,968,877,...,988,974,0.000000,988,974,0.000000,1120.292725,4676.091797,simulation00581.png,precision

In [45]:
df_f.to_csv('data/depths_and_z.csv',index=False)